/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message, Message, AUTO)


PB_BIND(RotaryChange, RotaryChange, AUTO)


PB_BIND(ButtonChange, ButtonChange, AUTO)





