/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_Message, protocol_Message, AUTO)


PB_BIND(protocol_RotaryChange, protocol_RotaryChange, AUTO)


PB_BIND(protocol_ButtonChange, protocol_ButtonChange, AUTO)





