/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Direction {
    Direction_CLOCKWISE = 0,
    Direction_COUNTERCLOCKWISE = 1
} Direction;

/* Struct definitions */
typedef struct _RotaryChange {
    bool has_index;
    int32_t index;
    bool has_direction;
    Direction direction;
} RotaryChange;

typedef struct _ButtonChange {
    bool has_index;
    int32_t index;
    bool has_pressed;
    bool pressed;
} ButtonChange;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Direction_MIN Direction_CLOCKWISE
#define _Direction_MAX Direction_COUNTERCLOCKWISE
#define _Direction_ARRAYSIZE ((Direction)(Direction_COUNTERCLOCKWISE+1))

#define RotaryChange_direction_ENUMTYPE Direction



/* Initializer values for message structs */
#define RotaryChange_init_default                {false, 0, false, _Direction_MIN}
#define ButtonChange_init_default                {false, 0, false, 0}
#define RotaryChange_init_zero                   {false, 0, false, _Direction_MIN}
#define ButtonChange_init_zero                   {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RotaryChange_index_tag                   1
#define RotaryChange_direction_tag               2
#define ButtonChange_index_tag                   1
#define ButtonChange_pressed_tag                 2

/* Struct field encoding specification for nanopb */
#define RotaryChange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    index,             1) \
X(a, STATIC,   OPTIONAL, UENUM,    direction,         2)
#define RotaryChange_CALLBACK NULL
#define RotaryChange_DEFAULT NULL

#define ButtonChange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    index,             1) \
X(a, STATIC,   OPTIONAL, BOOL,     pressed,           2)
#define ButtonChange_CALLBACK NULL
#define ButtonChange_DEFAULT NULL

extern const pb_msgdesc_t RotaryChange_msg;
extern const pb_msgdesc_t ButtonChange_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RotaryChange_fields &RotaryChange_msg
#define ButtonChange_fields &ButtonChange_msg

/* Maximum encoded size of messages (where known) */
#define ButtonChange_size                        13
#define PROTOCOL_PB_H_MAX_SIZE                   RotaryChange_size
#define RotaryChange_size                        13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
