M48
; DRILL file {KiCad 8.0.5-dirty} date 2024-11-08T09:41:07-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-08T09:41:07-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-dirty
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X1.9882Y-3.0512
X1.9882Y-3.9961
X9.626Y-3.0512
X9.626Y-3.9961
M30
